package com.apps.newstudio.tasklist.utils;

public interface ConstantsManager {

    String LANGUAGE_KEY = "LANGUAGE_KEY", LANGUAGE_ENG = "ENG", LANGUAGE_RUS = "RUS", LANGUAGE_UKR = "UKR";
    String FIRST_DAY_KEY = "FIRST_DAY_KEY", FIRST_DAY_MONDAY = "FIRST_DAY_MONDAY", FIRST_DAY_SUNDAY = "FIRST_DAY_SUNDAY";
    String LANGUAGE_CHOSEN_KEY = "LANGUAGE_CHOSEN_KEY";
    String LANGUAGE_CHOSEN = "LANGUAGE_CHOSEN";

    String SAVED_FRAGMENT_ID = "SAVED_FRAGMENT_ID";
    String TIME_STYLE_AM = "AM", TIME_STYLE_PM = "PM";

    int CATEGORIES_NONE = 0;
    int CATEGORIES_FAMILY = 1;
    int CATEGORIES_MEETINGS = 2;
    int CATEGORIES_HONE = 3;
    int CATEGORIES_SHOPPING = 4;
    int CATEGORIES_BIRTHDAY = 5;
    int CATEGORIES_BUSINESS = 6;
    int CATEGORIES_CALLS = 7;
    int CATEGORIES_ENTERTAINMENTS = 8;
    int CATEGORIES_EDUCATION = 9;
    int CATEGORIES_PETS = 10;
    int CATEGORIES_PRIVATE_LIFE = 11;
    int CATEGORIES_REPAIR = 12;
    int CATEGORIES_WORK = 13;
    int CATEGORIES_SPORT = 14;
    int CATEGORIES_TRAVELLINGS = 15;

    String TASK_ID_FLAG = "TASK_ACTIVITY_ID_FLAG";
    Long TASK_ID_NONE = -1L;
    String TASK_STATE_FLAG = "TASK_STATE_FLAG";
    int STATE_FLAG_ACTIVE = 0, STATE_FLAG_DONE = 1;
    String TASK_TITLE_FLAG = "TASK_TITLE_FLAG", TASK_CATEGORY_FLAG = "TASK_CATEGORY_FLAG";
    String TASK_DAY_FLAG = "TASK_DAY_FLAG", TASK_MONTH_FLAG = "TASK_MONTH_FLAG", TASK_YEAR_FLAG = "TASK_YEAR_FLAG";
    String TASK_HOUR_BEGINNING_FLAG = "TASK_HOUR_BEGINNING_FLAG", TASK_MINUTE_BEGINNING_FLAG = "TASK_MINUTE_BEGINNING_FLAG";
    String TASK_HOUR_END_FLAG = "TASK_HOUR_END_FLAG", TASK_MINUTE_END_FLAG = "TASK_MINUTE_END_FLAG";
    String ALARM_FLAG = "ALARM_FLAG", ALARM_HOUR_FLAG = "ALARM_HOUR_FLAG", ALARM_MINUTE_FLAG = "ALARM_MINUTE_FLAG";
    int ALARM_FLAG_ON = 1, ALARM_FLAG_OFF = 0;

    int TASK_REQUEST_CODE = 1;

    String CHOSEN_DAY_KEY = "CHOSEN_DAY_KEY";
    String CHOSEN_MONTH_KEY = "CHOSEN_MONTH_KEY";
    String CHOSEN_YEAR_KEY = "CHOSEN_YEAR_KEY";

    int DIALOG_LIST_TYPE_ONE = 1;
    int DIALOG_LIST_TYPE_TWO = 2;

    String TOTAL_ALARM_STATE_FLAG = "TOTAL_ALARM_STATE_FLAG";
    int TOTAL_ALARM_STATE_ON = 1, TOTAL_ALARM_STATE_OFF = 0;
    String TOTAL_ALARM_HOUR_FLAG = "TOTAL_ALARM_HOUR_FLAG", TOTAL_ALARM_MINUTE_FLAG = "TOTAL_ALARM_MINUTE_FLAG";
    int TOTAL_ALARM_HOUR_DEFAULT = 8, TOTAL_ALARM_MINUTE_DEFAULT = 0;
    String NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID";

    String UPDATE_ALL_WIDGETS = "UPDATE_ALL_WIDGETS";
    String UPDATE_WIDGET_LIST = "UPDATE_WIDGET_LIST";

    String WIDGET_TODAY_DAY_FLAG = "WIDGET_TODAY_DAY_FLAG";
    String WIDGET_TODAY_MONTH_FLAG = "WIDGET_TODAY_MONTH_FLAG";
    String WIDGET_TODAY_YEAR_FLAG = "WIDGET_TODAY_YEAR_FLAG";

    String WIDGET_CHOSEN_DAY_FLAG = "WIDGET_CHOSEN_DAY_FLAG";
    String WIDGET_CHOSEN_MONTH_FLAG = "WIDGET_CHOSEN_MONTH_FLAG";
    String WIDGET_CHOSEN_YEAR_FLAG = "WIDGET_CHOSEN_YEAR_FLAG";
    String WIDGET_CHOSEN_STATE_FLAG = "WIDGET_CHOSEN_STATE_FLAG";

    String WIDGET_ON_CLICK_STATE_ACTIVE = "WIDGET_ON_CLICK_STATE_ACTIVE";
    String WIDGET_ON_CLICK_STATE_DONE = "WIDGET_ON_CLICK_STATE_DONE";

    String WIDGET_ON_CLICK_LEFT = "WIDGET_ON_CLICK_LEFT";
    String WIDGET_ON_CLICK_RIGHT = "WIDGET_ON_CLICK_RIGHT";
    String WIDGET_ON_CLICK_ADD_NEW_TASK = "WIDGET_ON_CLICK_ADD_NEW_TASK";

    String WIDGET_ON_CLICK_LIST = "WIDGET_ON_CLICK_LIST";
    String WIDGET_ON_CLICK_LIST_ITEM_ID = "WIDGET_ON_CLICK_LIST_ITEM_ID";
    String WIDGET_ON_CLICK_LIST_ACTION_TAG = "WIDGET_ON_CLICK_LIST_ACTION_CHANGE";
    String WIDGET_ON_CLICK_LIST_ACTION_CHANGE = "WIDGET_ON_CLICK_LIST_ACTION_CHANGE";
    String WIDGET_ON_CLICK_LIST_ACTION_OPEN = "WIDGET_ON_CLICK_LIST_ACTION_OPEN";




}
